defaults:
  why: "Низкая оценка раздела может привести к юридическим рискам."
sections:
  - key: parties
    title: "Идентификация сторон, полномочия, реквизиты"
    weight: 8
    why: "Ошибки в реквизитах/полномочиях делают договор оспоримым."
    suggestion: "Проверить ОГРН/ИНН, полномочия, доверенности/ЭП."
  - key: scope
    title: "Предмет/результат, измеримость (SOW/ТЗ)"
    weight: 10
    why: "Неясный предмет лишает договор исполнимости и мешает приемке."
    suggestion: "Прописать измеримый результат/ТЗ и критерии приемки."
  - key: timeline_acceptance
    title: "Сроки, поставка/оказание, приемка, milestones"
    weight: 8
    why: "Нет процедуры приемки — спорно, когда обязательства исполнены."
    suggestion: "Ввести форму акта, сроки и последствия просрочки."
  - key: payment
    title: "Цена, налоги, порядок платежей, удержания"
    weight: 10
    why: "Неопределённая цена/сроки оплаты создают риски споров и кассовых разрывов."
    suggestion: "Зафиксировать цену/сроки оплаты, аванс/удержания, налоги."
  - key: liability
    title: "Ответственность, неустойки/штрафы, лимиты (cap)"
    weight: 10
    why: "Отсутствие лимита ответственности ведёт к непропорциональным рискам."
    suggestion: "Установить cap ответственности и исключения."
  - key: reps_warranties
    title: "Гарантии и заверения сторон"
    weight: 6
    why: "Без заверений растут риски недостоверных сведений."
    suggestion: "Заверения об отсутствии прав третьих лиц."
  - key: ip
    title: "IP/права на результаты, лицензии, отчуждение"
    weight: 8
    why: "Без явной передачи/лицензии права на результаты могут остаться у исполнителя."
    suggestion: "Определить передачу/лицензию прав: объём, территория, срок."
  - key: confidentiality
    title: "Конфиденциальность/коммерческая тайна"
    weight: 6
    why: "Без NDA утечка сведений не контролируется."
    suggestion: "Задать режим тайны, срок, исключения и ответственность."
  - key: personal_data
    title: "Персональные данные/данные (GDPR/152-ФЗ и пр.)"
    weight: 8
    why: "Нарушения по ПДн чреваты штрафами и запретом обработки."
    suggestion: "Добавить DPA/152-ФЗ: роли, цели, трансграничку, меры."
  - key: force_majeure
    title: "Форс-мажор"
    weight: 4
    why: "Нечёткий форс-мажор — злоупотребления и неопределённость."
    suggestion: "Согласовать перечень событий и порядок уведомления."
  - key: change_termination
    title: "Изменение/расторжение, односторонний отказ"
    weight: 6
    why: "Односторонние изменения без триггеров — дисбаланс и риски."
    suggestion: "Определить основания и уведомления."
  - key: law_venue
    title: "Применимое право и подсудность/арбитраж"
    weight: 6
    why: "Без права и подсудности сложнее защищать интересы и исполнять решения."
    suggestion: "Указать право РФ и подсудность/арбитраж."
  - key: conflicts_priority
    title: "Конфликты/приоритет документов, приложения"
    weight: 5
    why: "Конфликт документов рушит логику договора."
    suggestion: "Добавить правило приоритета и реестр приложений."
  - key: signatures_form
    title: "Подписи, форма сделки, экземпляры/ЭП"
    weight: 5
    why: "Ошибки в форме/подписи ведут к недействительности."
    suggestion: "Указать форму (бумага/ЭП), экз., порядок обмена."
